# package name for repository
# the name should be all lowercase with -+.
package_name: hello-world

maintainer:
  name: LiJianying
  email: lijy91@foxmail.com

# the size of binary in kilobyte
installed_size: 6604

postinstall_scripts:
  - echo `Installed my awesome app`
postuninstall_scripts:
  - echo `Surprised Pickachu face`
